#!/bin/bash

set -e

#export PATH="/opt/x-tools/armv6-rpi-linux-gnueabihf/bin:$PATH"
#export CFLAGS="-Wall -O3 -mcpu=cortex-a7 -mfpu=vfp -mfloat-abi=hard"
#export CXXFLAGS="-Wall -O3 -mcpu=cortex-a7 -mfpu=vfp -mfloat-abi=hard"
#export CROSS_COMPILE="armv6-rpi-linux-gnueabihf-"
#triple=armv6-rpi-linux-gnueabihf
#variant_triple=armv6-rpi2-linux-gnueabihf

BOOST_DIR=$HOME/src/cpp/boost
LIBINST_PREFIX=$HOME/src/cpp/inst
#BOOST_DIR=/opt/x-tools/$triple/$triple/sysroot/usr/local
#LIBINST_PREFIX=$BOOST_DIR

cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug \
  -DCMAKE_PREFIX_PATH=$LIBINST_PREFIX \
  -DBoost_INCLUDE_DIR=$BOOST_DIR/include \
  -Dtgbot-cpp_DIR=$LIBINST_PREFIX
#  --toolchain /opt/x-tools/$triple/$variant_triple.toolchain.cmake \
#  -DBUILD_TESTING=OFF

cmake --build build
#cmake --install build
#make DESTDIR=/opt/x-tools/$triple/$triple/sysroot install

ctest --test-dir build --output-on-failure

