#!/bin/bash

set -e

BOOST_DIR=$HOME/src/cpp/boost
LIBINST_PREFIX=$HOME/src/cpp/inst

cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug \
  -DCMAKE_PREFIX_PATH=$LIBINST_PREFIX \
  -DBoost_INCLUDE_DIR=$BOOST_DIR/include \
  -Dtgbot-cpp_DIR=$LIBINST_PREFIX
#  -DBUILD_TESTING=OFF

cmake --build build
#cmake --install build

